name: 'Action Usage Guard'
description: 'A GitHub Action that cancels workflows if total account usage exceeds a defined threshold.'
author: 'nekofar'
branding:
  icon: 'activity'
  color: 'red'

inputs:
  token:
    description: 'GitHub access token to authenticate with the repository.'
    required: true

  threshold:
    description: 'The maximum usage limit before workflows are cancelled.'
    required: false
    default: '70'

runs:
  using: 'composite'
  steps:
    - run: ${{ github.action_path }}/entrypoint.sh
      shell: 'bash'
      env:
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_THRESHOLD: ${{ inputs.threshold }}
